image: node:latest

cache:
  paths:
    - node_modules/

deploy_production:
  stage: deploy
  environment: Production
  only:
    - tags
  script:
    - npm -v
    - npm install -g universal-analytics
    - npm install -g firebase-tools
    - npm install
    - firebase use --token $FIREBASE_DEPLOY_KEY $FIREBASE_PROJ_CODE
    - ls
    - npm run build
    - ls
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
