const fs = require('fs');
const path = require('path');

// Load .env file for local dev (dotenv-style, manual parse to avoid extra dependencies)
function loadEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return;
  const lines = fs.readFileSync(filePath, 'utf8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const value = trimmed.slice(eqIdx + 1).trim().replace(/^["']|["']$/g, '');
    if (!(key in process.env)) process.env[key] = value;
  }
}

loadEnvFile(path.join(__dirname, '.env'));
loadEnvFile(path.join(__dirname, '.env.local'));

function readExistingEnvironmentValue(filePath, propertyName) {
  if (!fs.existsSync(filePath)) return '';
  const content = fs.readFileSync(filePath, 'utf8');
  return content.match(new RegExp(`${propertyName}:\\\\s*['"]([^'"]+)['"]`))?.[1] || '';
}

const existingDevEnvPath = path.join(__dirname, 'src/environments/environment.ts');
const supabaseUrl = process.env.SUPABASE_URL || readExistingEnvironmentValue(existingDevEnvPath, 'url');
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || readExistingEnvironmentValue(existingDevEnvPath, 'key');

if (!supabaseUrl || !supabaseAnonKey) {
  console.warn('[generate-env] WARNING: SUPABASE_URL or SUPABASE_ANON_KEY is not set. Environment files will have empty values.');
}

const prodEnvContent = `
export const environment = {
  production: true,
  supabase: {
    url: '${supabaseUrl}', // SAFE to expose — anon key with RLS enforced
    key: '${supabaseAnonKey}' // SAFE to expose — anon key with RLS enforced
  },
  features: {
    collectionsEnabled: false,
    coolReactionsEnabled: false,
    marketplaceEnabled: false
  }
};
`;

const devEnvContent = `
// ⚠️ This file is gitignored and must NEVER be committed.
// Generated by generate-env.js — run: node generate-env.js
export const environment = {
  production: false,
  supabase: {
    url: '${supabaseUrl}', // SAFE to expose — anon key with RLS enforced
    key: '${supabaseAnonKey}' // SAFE to expose — anon key with RLS enforced
  },
  features: {
    collectionsEnabled: true,
    coolReactionsEnabled: true,
    marketplaceEnabled: true
  }
};
`;

fs.writeFileSync('src/environments/environment.prod.ts', prodEnvContent);
fs.writeFileSync('src/environments/environment.ts', devEnvContent);

console.log('[generate-env] environment.ts and environment.prod.ts written.');