const fs = require('fs');
const path = require('path');

// Load .env file for local dev (dotenv-style, manual parse to avoid extra dependencies)
function loadEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return;
  const lines = fs.readFileSync(filePath, 'utf8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const value = trimmed.slice(eqIdx + 1).trim().replace(/^["']|["']$/g, '');
    if (!(key in process.env)) process.env[key] = value;
  }
}

loadEnvFile(path.join(__dirname, '.env'));
loadEnvFile(path.join(__dirname, '.env.local'));

const DEFAULT_SUPABASE_URL = 'https://sozmatmywjpstwidzlss.supabase.co';

function readExistingEnvironmentValue(filePath, propertyName) {
  if (!fs.existsSync(filePath)) return '';
  const content = fs.readFileSync(filePath, 'utf8');
  return content.match(new RegExp(`${propertyName}:\\s*['"]([^'"]+)['"]`))?.[1] || '';
}

const existingDevEnvPath = path.join(__dirname, 'src/environments/environment.ts');
const supabaseUrl = process.env.SUPABASE_URL || readExistingEnvironmentValue(existingDevEnvPath, 'url') || DEFAULT_SUPABASE_URL;
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || readExistingEnvironmentValue(existingDevEnvPath, 'key');

if (!supabaseAnonKey) {
  console.warn('[generate-env] WARNING: SUPABASE_ANON_KEY is not set. Environment files will have an empty anon key.');
}

// Turnstile site keys are public. Empty disables the captcha widget (prod until the self-host cutover).
const DEV_TURNSTILE_SITE_KEY = '0x4AAAAAAFNy2CcbfwOPeWeo';
const prodTurnstileSiteKey = process.env.TURNSTILE_SITE_KEY || '';
const devTurnstileSiteKey = process.env.TURNSTILE_SITE_KEY ?? DEV_TURNSTILE_SITE_KEY;

// Single source of truth for feature flags; middleware.ts imports the production block too.
const featureFlags = require('./src/environments/features.json');

function renderFeatures(flags) {
  return Object.entries(flags).map(([name, enabled]) => `    ${name}: ${enabled}`).join(',\n');
}

const prodEnvContent = `
export const environment = {
  production: true,
  supabase: {
    url: '${supabaseUrl}', // SAFE to expose — anon key with RLS enforced
    key: '${supabaseAnonKey}' // SAFE to expose — anon key with RLS enforced
  },
  turnstileSiteKey: '${prodTurnstileSiteKey}',
  features: {
${renderFeatures(featureFlags.production)}
  }
};
`;

const devEnvContent = `
// ⚠️ This file is gitignored and must NEVER be committed.
// Generated by generate-env.js — run: node generate-env.js
export const environment = {
  production: false,
  supabase: {
    url: '${supabaseUrl}', // SAFE to expose — anon key with RLS enforced
    key: '${supabaseAnonKey}' // SAFE to expose — anon key with RLS enforced
  },
  turnstileSiteKey: '${devTurnstileSiteKey}',
  features: {
${renderFeatures(featureFlags.development)}
  }
};
`;

fs.writeFileSync('src/environments/environment.prod.ts', prodEnvContent);
fs.writeFileSync('src/environments/environment.ts', devEnvContent);

console.log('[generate-env] environment.ts and environment.prod.ts written.');