#!/usr/bin/env bash
#
# Capture the source database's ownership + privilege state as a replayable SQL
# file, and replay it onto the self-host. Replaces the blanket
# staging-public-grants.sql with the source's exact grants.
#
#   capture  (read-only) SOURCE_DB_URL -> backups/grants-replay-<ts>.sql
#            Runs with default_transaction_read_only=on; also runs the
#            least-privilege audit against the source and reports it.
#   apply    TARGET_DB_URL <- file. Default is a REHEARSAL: the whole file runs
#            inside BEGIN ... ROLLBACK, so errors and the audit show without
#            changing anything. --commit runs it in a single transaction.
#
# What the replay sets (scope in lib/grants-replay-generate.sql):
#   owners of schemas/types/tables/views/sequences/routines in public+private;
#   effective ACLs of those objects + column grants + public/private/storage
#   schema ACLs; default privileges; custom roles (NOLOGIN only) + memberships;
#   storage policies; on PG17+ targets MAINTAIN joins every full PG15 grant
#   (lib/grants-replay-pg17.sql). Ends with the api_v1 least-privilege audit — any
#   violation aborts the transaction.
#
# Safety: apply refuses targets without the patcher_selfhost_marker role, URLs
# that look hosted, and non-superuser sessions (the file re-checks marker +
# superuser itself, so it is safe even if piped by hand). Connection strings
# are never printed. Output lives in gitignored backups/.
#
# Usage:
#   SOURCE_DB_URL=... bash scripts/ops/capture-grants.sh capture
#   TARGET_DB_URL=... bash scripts/ops/capture-grants.sh apply backups/grants-replay-<ts>.sql [--commit]
#   bash scripts/ops/capture-grants.sh audit   # TARGET_DB_URL or SOURCE_DB_URL, read-only

set -euo pipefail
umask 077

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
# shellcheck source=lib/pg-common.sh
source "${SCRIPT_DIR}/lib/pg-common.sh"

GENERATE_SQL="${SCRIPT_DIR}/lib/grants-replay-generate.sql"
PRELUDE_SQL="${SCRIPT_DIR}/lib/grants-replay-prelude.sql"
PG17_SQL="${SCRIPT_DIR}/lib/grants-replay-pg17.sql"
AUDIT_SQL="${SCRIPT_DIR}/lib/grants-replay-audit.sql"
BACKUP_DIR="${REPO_ROOT}/backups"

usage() { sed -n '2,29p' "$0" | sed 's/^# \{0,1\}//'; }

cmd="${1:-}"
[ $# -gt 0 ] && shift
case "${cmd}" in
  -h|--help) usage; exit 0 ;;
  "") usage >&2; exit 1 ;;
  capture|apply|audit) ;;
  *) echo "ERROR: unknown command: ${cmd}" >&2; usage >&2; exit 1 ;;
esac

command -v psql >/dev/null 2>&1 || { echo "ERROR: required command not found: psql" >&2; exit 1; }

run_audit() {
  local url="$1"
  psql "${url}" -X -q -v ON_ERROR_STOP=1 -c "SET search_path = pg_catalog;" -f "${AUDIT_SQL}" 2>&1
}

if [ "${cmd}" = "capture" ]; then
  [ $# -eq 0 ] || { echo "ERROR: capture takes no arguments." >&2; exit 1; }
  [ -n "${SOURCE_DB_URL:-}" ] || { echo "ERROR: SOURCE_DB_URL must be set in the shell (never commit it)." >&2; exit 1; }
  require_not_selfhost_source "${SOURCE_DB_URL}"
  if git -C "${REPO_ROOT}" rev-parse --is-inside-work-tree >/dev/null 2>&1 \
     && ! git -C "${REPO_ROOT}" check-ignore -q "backups/"; then
    echo "ERROR: backups/ is not ignored by git. Refusing to write." >&2; exit 1
  fi
  mkdir -p "${BACKUP_DIR}"; chmod 700 "${BACKUP_DIR}"
  out="${BACKUP_DIR}/grants-replay-$(date -u +%Y%m%dT%H%M%SZ).sql"
  body="$(mktemp)"; trap 'rm -f "${body}"' EXIT

  PGOPTIONS="${PGOPTIONS} -c default_transaction_read_only=on -c search_path=pg_catalog" \
    psql "${SOURCE_DB_URL}" -X -q -tA -v ON_ERROR_STOP=1 -f "${GENERATE_SQL}" > "${body}"

  {
    echo "-- Patcher grants/ownership replay — GENERATED by scripts/ops/capture-grants.sh; do not edit."
    echo "-- Apply only via: TARGET_DB_URL=... bash scripts/ops/capture-grants.sh apply <this file> [--commit]"
    echo "-- No secrets, no row data, no connection strings. Keep in gitignored backups/."
    echo
    cat "${PRELUDE_SQL}"
    echo
    cat "${body}"
    echo
    cat "${PG17_SQL}"
    echo
    echo "-- 7. Least-privilege audit (aborts the transaction on any violation)"
    cat "${AUDIT_SQL}"
  } > "${out}"
  chmod 600 "${out}"

  count() { grep -c "$1" "${body}" || true; }
  echo "Captured (read-only): ${out#"${REPO_ROOT}"/}"
  echo "  owners: $(count '^ALTER .* OWNER TO')  object grants: $(count '^GRANT .* ON ')  column grants: $(count '^GRANT [A-Z]* (')"
  echo "  default-privilege grants: $(count '^ALTER DEFAULT PRIVILEGES')  memberships: $(count 'ensure_membership')  storage policies: $(count '^CREATE POLICY')"
  echo "Source least-privilege audit:"
  if audit_out="$(PGOPTIONS="${PGOPTIONS} -c default_transaction_read_only=on" run_audit "${SOURCE_DB_URL}")"; then
    echo "  ${audit_out:-OK}" | sed 's/^  NOTICE:  /  /'
  else
    echo "  FAILED on the source — the replay will abort on the target until this is resolved:"
    echo "${audit_out}" | sed 's/^/  /'
  fi
  echo "Next: TARGET_DB_URL=... bash scripts/ops/capture-grants.sh apply ${out#"${REPO_ROOT}"/}   (rehearsal; add --commit to keep)"
  exit 0
fi

if [ "${cmd}" = "audit" ]; then
  url="${TARGET_DB_URL:-${SOURCE_DB_URL:-}}"
  [ -n "${url}" ] || { echo "ERROR: set TARGET_DB_URL or SOURCE_DB_URL." >&2; exit 1; }
  PGOPTIONS="${PGOPTIONS} -c default_transaction_read_only=on" run_audit "${url}"
  exit $?
fi

# apply
file="" commit=0
for arg in "$@"; do
  case "${arg}" in
    --commit) commit=1 ;;
    -*) echo "ERROR: unknown option: ${arg}" >&2; exit 1 ;;
    *) [ -z "${file}" ] || { echo "ERROR: one replay file only." >&2; exit 1; }; file="${arg}" ;;
  esac
done
[ -n "${file}" ] && [ -f "${file}" ] || { echo "ERROR: apply needs an existing replay file." >&2; exit 1; }
head -1 "${file}" | grep -q '^-- Patcher grants/ownership replay — GENERATED' \
  || { echo "ERROR: ${file} is not a capture-grants replay file." >&2; exit 1; }
[ -n "${TARGET_DB_URL:-}" ] || { echo "ERROR: TARGET_DB_URL must be set in the shell (never commit it)." >&2; exit 1; }

require_staging_target "${TARGET_DB_URL}"
[ "$(pg_q "${TARGET_DB_URL}" "SELECT rolsuper FROM pg_roles WHERE rolname = current_user;")" = "t" ] || {
  echo "ERROR: connect as a superuser (self-host: supabase_admin); ownership and other roles' grants need it." >&2; exit 1; }

echo "Target: $(mask_db_url "${TARGET_DB_URL}")"
rc=0
if [ "${commit}" -eq 1 ]; then
  echo "Mode: COMMIT (single transaction; any error or audit failure rolls everything back)"
  log="$(psql "${TARGET_DB_URL}" -X -q -v ON_ERROR_STOP=1 --single-transaction -f "${file}" 2>&1)" || rc=$?
else
  echo "Mode: REHEARSAL (BEGIN ... ROLLBACK — nothing is kept). Re-run with --commit to apply."
  log="$({ echo 'BEGIN;'; cat "${file}"; echo; echo 'ROLLBACK;'; } \
    | psql "${TARGET_DB_URL}" -X -q -v ON_ERROR_STOP=1 2>&1)" || rc=$?
fi
# Skip per-object helper chatter; keep warnings, errors and the audit verdict.
grep -E 'WARNING|ERROR|FATAL|audit|LINE|DETAIL|CONTEXT' <<< "${log}" | grep -v '^$' || true
if [ "${rc}" -ne 0 ]; then
  echo "FAILED (psql exit ${rc}) — nothing was changed." >&2; exit 1
fi
if [ "${commit}" -eq 1 ]; then
  echo "Replay committed. Verify: SOURCE_DB_URL=... TARGET_DB_URL=... pnpm verify:staging-parity:deep --only privileges (and views, policies)."
else
  echo "Rehearsal passed (rolled back)."
fi
