#!/usr/bin/env python3
"""Generate an API-only Envoy listener for the public tunnel (checklist H5).

Runs ON the self-host server (piped over ssh by selfhost-public-listener.sh).
Copies the upstream `supabase` listener from lds.template.yaml into a second
listener `supabase-public` on PUBLIC_PORT that keeps only the routes the
Cloudflare hostname allows (^/(rest|auth|storage|functions|realtime)/v1/) and
answers everything else (Studio, /pg/, /mcp, graphql, ...) with 404. Studio stays
on the LAN listener only. Idempotent: the generated block is replaced on re-run,
so re-apply after every upstream upgrade of the envoy template.

Usage: python3 - <template_path> <out_path> [port] < envoy-public-listener.py
"""
import copy
import re
import sys

import yaml

BEGIN = "# BEGIN supabase-public (generated by scripts/ops/selfhost-public-listener.sh; do not edit)"
END = "# END supabase-public"
ALLOWED = re.compile(r"^/(rest|auth|storage|functions|realtime)/v1(/|$)")

src, out = sys.argv[1], sys.argv[2]
port = int(sys.argv[3]) if len(sys.argv) > 3 else 8001

text = open(src).read()
if BEGIN in text:
    text = text[: text.index(BEGIN)].rstrip("\n") + "\n"

doc = yaml.safe_load(text)
if list(doc) != ["resources"]:
    sys.exit("unexpected template layout: top-level keys %s" % list(doc))
names = [r.get("name") for r in doc["resources"]]
if names != ["supabase"]:
    sys.exit("unexpected listeners %s (expected only 'supabase')" % names)

pub = copy.deepcopy(doc["resources"][0])
pub["name"] = "supabase-public"
pub["address"]["socket_address"]["port_value"] = port
if len(pub["filter_chains"]) != 1:
    sys.exit("expected one filter chain")
hcm = pub["filter_chains"][0]["filters"][0]["typed_config"]
hcm["stat_prefix"] = "ingress_http_public"
vhosts = hcm["route_config"]["virtual_hosts"]
if len(vhosts) != 1:
    sys.exit("expected one virtual host")
hcm["route_config"]["name"] = "supabase-public"

kept, dropped = [], []
for r in vhosts[0]["routes"]:
    m = r["match"]
    p = m.get("prefix") or m.get("path")
    (kept if p and ALLOWED.match(p) else dropped).append(r)
if not any((r["match"].get("prefix") or "") == "/rest/v1/" for r in kept):
    sys.exit("no /rest/v1/ route found; template changed upstream, review by hand")

allow_all = {
    "envoy.filters.http.rbac": {
        "@type": "type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBACPerRoute",
        "rbac": {"rules": {"action": "ALLOW", "policies": {"allow_all": {
            "permissions": [{"any": True}], "principals": [{"any": True}]}}}},
    },
    "envoy.filters.http.basic_auth": {
        "@type": "type.googleapis.com/envoy.config.route.v3.FilterConfig",
        "disabled": True,
    },
}
kept.append({
    "name": "public-not-found",
    "match": {"prefix": "/"},
    "direct_response": {"status": 404, "body": {"inline_string": "not found\n"}},
    "typed_per_filter_config": allow_all,
})
vhosts[0]["routes"] = kept


class Dumper(yaml.SafeDumper):
    pass


def _str(dumper, s):
    # Block style for code; single quotes around ${...} placeholders (as upstream does),
    # since the entrypoint substitutes raw secrets into them with sed.
    style = "|" if "\n" in s else ("'" if "${" in s else None)
    return dumper.represent_scalar("tag:yaml.org,2002:str", s, style=style)


Dumper.add_representer(str, _str)
body = yaml.dump([pub], Dumper=Dumper, sort_keys=False, default_flow_style=False, width=4096)
block = "\n".join(("  " + l) if l else l for l in body.rstrip("\n").split("\n"))

result = text.rstrip("\n") + "\n\n" + BEGIN + "\n" + block + "\n" + END + "\n"
check = yaml.safe_load(result)
if [r["name"] for r in check["resources"]] != ["supabase", "supabase-public"]:
    sys.exit("generated file does not round-trip")
if check["resources"][0] != doc["resources"][0]:
    sys.exit("LAN listener changed during generation; aborting")
open(out, "w").write(result)

print("public listener port %d" % port)
print("kept:    " + ", ".join(r.get("name") or (r["match"].get("prefix") or r["match"].get("path")) for r in kept))
print("dropped: " + ", ".join(r.get("name") or (r["match"].get("prefix") or r["match"].get("path")) for r in dropped))
