// Build information, automatically generated by `ng-info`
const build = {
    version:   '2.8.6',
    timestamp: 'Wed May 19 2021 00:17:02 GMT+0200 (Ora legale dell’Europa centrale)',
    message:   null,
    git:       {
        user:     'Vlady Yakovenko',
        branch:   'master',
        hash:     '46e845',
        fullHash: '46e8458fd64b3fd0575d75c92ae1cf3702098a1d'
    }
};

export default build;
