// Build information, automatically generated by `ng-info`
const build = {
  version:   '0.11.0',
  timestamp: 'Sat Apr 24 2021 20:51:14 GMT+0200 (Ora legale dell’Europa centrale)',
  message:   null,
  git:       {
    user:     'Vlady Yakovenko',
    branch:   'master',
    hash:     '492e90',
    fullHash: '492e90077cad59b9a7de372c9410fafaa67c26e0'
  }
};

export default build;
