// Build information, automatically generated by `ng-info`
const build = {
  version:   '4.1.1',
  timestamp: 'Thu Jan 25 2024 09:45:35 GMT+0100 (Central European Standard Time)',
    message: null,
    git: {
      user:     'Vladyslav Yakovenko',
      branch:   'sweep/allowe_to_copy_name_and_company_of_modul',
      hash:     'd7f7ea',
      fullHash: 'd7f7eaaaf77baa8933a0be7a089af33e3ed3b9bf'
    }
};

export default build;