-- Module collections MVP: private-by-default playlists of modules with ordered entries.
-- No RLS/policy changes are included here per repo instruction.

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.module_collections (
  id bigint generated by default as identity primary key,
  authorid uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  description text,
  image text,
  public boolean not null default false,
  public_id text not null default public.generate_public_id(),
  created timestamp without time zone not null default now(),
  updated timestamp without time zone not null default now()
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'module_collections_name_not_blank'
      and conrelid = 'public.module_collections'::regclass
  ) then
    alter table public.module_collections
      add constraint module_collections_name_not_blank check (length(btrim(name)) > 0);
  end if;
end;
$$;

create index if not exists module_collections_authorid_idx on public.module_collections (authorid);
create index if not exists module_collections_public_updated_idx on public.module_collections (public, updated desc, id desc);
create unique index if not exists module_collections_public_id_uniq on public.module_collections (public_id);

drop trigger if exists trg_module_collections_public_id on public.module_collections;
create trigger trg_module_collections_public_id
  before insert on public.module_collections
  for each row execute function public.tg_set_public_id();

create table if not exists public.module_collection_entries (
  id bigint generated by default as identity primary key,
  collection_id bigint not null references public.module_collections(id) on delete cascade,
  module_id bigint not null references public.modules(id),
  ordinal integer not null,
  note text,
  created timestamp without time zone not null default now(),
  updated timestamp without time zone not null default now(),
  unique (collection_id, module_id),
  unique (collection_id, ordinal)
);

create index if not exists module_collection_entries_collection_idx on public.module_collection_entries (collection_id, ordinal);
create index if not exists module_collection_entries_module_idx on public.module_collection_entries (module_id);

create or replace function public.tg_touch_module_collection_updated()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  NEW.updated = now();
  return NEW;
end;
$$;

comment on function public.tg_touch_module_collection_updated() is
  'BEFORE UPDATE trigger: keeps module_collections.updated aligned with direct collection metadata changes.';

drop trigger if exists trg_touch_module_collection_updated on public.module_collections;
create trigger trg_touch_module_collection_updated
  before update on public.module_collections
  for each row execute function public.tg_touch_module_collection_updated();

create or replace function public.tg_touch_module_collection_updated_from_entries()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.module_collections
     set updated = now()
   where id = coalesce(NEW.collection_id, OLD.collection_id);
  return null;
end;
$$;

comment on function public.tg_touch_module_collection_updated_from_entries() is
  'AFTER INSERT/UPDATE/DELETE trigger: bumps module_collections.updated whenever entries change.';

drop trigger if exists trg_touch_module_collection_updated_from_entries on public.module_collection_entries;
create trigger trg_touch_module_collection_updated_from_entries
  after insert or update or delete on public.module_collection_entries
  for each row execute function public.tg_touch_module_collection_updated_from_entries();

create or replace function public.save_module_collection(
  p_name text,
  p_collection_id bigint default null,
  p_description text default null,
  p_public boolean default false,
  p_image text default null,
  p_module_ids bigint[] default '{}'::bigint[]
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_collection_id bigint;
  v_module_count int;
begin
  if v_user_id is null then
    raise exception 'Authentication required';
  end if;

  if p_collection_id is null then
    insert into public.module_collections (authorid, name, description, public, image)
    values (v_user_id, btrim(p_name), nullif(btrim(coalesce(p_description, '')), ''), coalesce(p_public, false), p_image)
    returning id into v_collection_id;
  else
    update public.module_collections
       set name = btrim(p_name),
           description = nullif(btrim(coalesce(p_description, '')), ''),
           public = coalesce(p_public, false),
           image = p_image,
           updated = now()
     where id = p_collection_id
       and authorid = v_user_id
     returning id into v_collection_id;

    if v_collection_id is null then
      raise exception 'Collection not found or not owned by current user';
    end if;
  end if;

  select count(*)::int
    into v_module_count
  from unnest(coalesce(p_module_ids, '{}'::bigint[])) as module_ids(module_id)
  left join public.modules m on m.id = module_ids.module_id
  where m.id is null or m.public is not true;

  if v_module_count > 0 then
    raise exception 'Collections can only contain public modules';
  end if;

  delete from public.module_collection_entries
   where collection_id = v_collection_id;

  insert into public.module_collection_entries (collection_id, module_id, ordinal)
  select v_collection_id, module_id, ordinality::int
  from unnest(coalesce(p_module_ids, '{}'::bigint[])) with ordinality as ids(module_id, ordinality);

  return v_collection_id;
end;
$$;

comment on function public.save_module_collection(text, bigint, text, boolean, text, bigint[]) is
  'Creates or updates a module collection and replaces its ordered module entry list.';

create or replace function public.delete_module_collection(
  p_collection_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null then
    raise exception 'Authentication required';
  end if;

  delete from public.module_collections
   where id = p_collection_id
     and authorid = v_user_id;

  if not found then
    raise exception 'Collection not found or not owned by current user';
  end if;
end;
$$;

comment on function public.delete_module_collection(bigint) is
  'Deletes one owned module collection and its entries.';

create or replace function public.get_public_module_collections(
  p_from int default 0,
  p_to int default 24
)
returns table (
  id bigint,
  authorid uuid,
  name text,
  description text,
  image text,
  public boolean,
  public_id text,
  created timestamp without time zone,
  updated timestamp without time zone,
  author jsonb,
  module_count integer
)
language sql
stable
security definer
set search_path = public
as $$
  select
    c.id,
    c.authorid,
    c.name,
    c.description,
    c.image,
    c.public,
    c.public_id,
    c.created,
    c.updated,
    jsonb_build_object('id', p.id, 'username', p.username) as author,
    coalesce((
      select count(*)
      from public.module_collection_entries e
      where e.collection_id = c.id
    ), 0)::int as module_count
  from public.module_collections c
  left join public.profiles p on p.id = c.authorid
  where c.public = true
  order by c.updated desc, c.id desc
  offset greatest(p_from, 0)
  limit greatest(p_to - p_from + 1, 0);
$$;

comment on function public.get_public_module_collections(int, int) is
  'Public module collection browser list ordered by recent activity.';

create or replace function public.get_current_user_module_collections(
  p_from int default 0,
  p_to int default 24
)
returns table (
  id bigint,
  authorid uuid,
  name text,
  description text,
  image text,
  public boolean,
  public_id text,
  created timestamp without time zone,
  updated timestamp without time zone,
  author jsonb,
  module_count integer
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null then
    raise exception 'Authentication required';
  end if;

  return query
  select
    c.id,
    c.authorid,
    c.name,
    c.description,
    c.image,
    c.public,
    c.public_id,
    c.created,
    c.updated,
    jsonb_build_object('id', p.id, 'username', p.username) as author,
    coalesce((
      select count(*)
      from public.module_collection_entries e
      where e.collection_id = c.id
    ), 0)::int as module_count
  from public.module_collections c
  left join public.profiles p on p.id = c.authorid
  where c.authorid = v_user_id
  order by c.updated desc, c.id desc
  offset greatest(p_from, 0)
  limit greatest(p_to - p_from + 1, 0);
end;
$$;

comment on function public.get_current_user_module_collections(int, int) is
  'Current-user module collection list ordered by recent activity.';

create or replace function public.get_public_module_collection_by_public_id(
  p_public_id text
)
returns table (
  id bigint,
  authorid uuid,
  name text,
  description text,
  image text,
  public boolean,
  public_id text,
  created timestamp without time zone,
  updated timestamp without time zone,
  author jsonb,
  entries jsonb,
  module_count integer
)
language sql
stable
security definer
set search_path = public
as $$
  select
    c.id,
    c.authorid,
    c.name,
    c.description,
    c.image,
    c.public,
    c.public_id,
    c.created,
    c.updated,
    jsonb_build_object('id', p.id, 'username', p.username) as author,
    coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', e.id,
          'ordinal', e.ordinal,
          'note', e.note,
          'module', jsonb_build_object(
            'id', m.id,
            'name', m.name,
            'description', m.description,
            'hp', m.hp,
            'public', m.public,
            'manufacturer', jsonb_build_object('id', mf.id, 'name', mf.name),
            'standard', jsonb_build_object('id', s.id, 'name', s.name),
            'created', m.created,
            'updated', m.updated
          )
        )
        order by e.ordinal
      )
      from public.module_collection_entries e
      join public.modules m on m.id = e.module_id and m.public = true
      left join public.manufacturers mf on mf.id = m."manufacturerId"
      left join public.standards s on s.id = m.standard
      where e.collection_id = c.id
    ), '[]'::jsonb) as entries,
    coalesce((
      select count(*)
      from public.module_collection_entries e
      join public.modules m on m.id = e.module_id and m.public = true
      where e.collection_id = c.id
    ), 0)::int as module_count
  from public.module_collections c
  left join public.profiles p on p.id = c.authorid
  where c.public_id = p_public_id
    and c.public = true
  limit 1;
$$;

comment on function public.get_public_module_collection_by_public_id(text) is
  'Public module collection detail read by opaque token.';

create or replace function public.get_current_user_module_collection_by_id(
  p_collection_id bigint
)
returns table (
  id bigint,
  authorid uuid,
  name text,
  description text,
  image text,
  public boolean,
  public_id text,
  created timestamp without time zone,
  updated timestamp without time zone,
  author jsonb,
  entries jsonb,
  module_count integer
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null then
    raise exception 'Authentication required';
  end if;

  return query
  select
    c.id,
    c.authorid,
    c.name,
    c.description,
    c.image,
    c.public,
    c.public_id,
    c.created,
    c.updated,
    jsonb_build_object('id', p.id, 'username', p.username) as author,
    coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', e.id,
          'ordinal', e.ordinal,
          'note', e.note,
          'module', jsonb_build_object(
            'id', m.id,
            'name', m.name,
            'description', m.description,
            'hp', m.hp,
            'public', m.public,
            'manufacturer', jsonb_build_object('id', mf.id, 'name', mf.name),
            'standard', jsonb_build_object('id', s.id, 'name', s.name),
            'created', m.created,
            'updated', m.updated
          )
        )
        order by e.ordinal
      )
      from public.module_collection_entries e
      join public.modules m on m.id = e.module_id and m.public = true
      left join public.manufacturers mf on mf.id = m."manufacturerId"
      left join public.standards s on s.id = m.standard
      where e.collection_id = c.id
    ), '[]'::jsonb) as entries,
    coalesce((
      select count(*)
      from public.module_collection_entries e
      join public.modules m on m.id = e.module_id and m.public = true
      where e.collection_id = c.id
    ), 0)::int as module_count
  from public.module_collections c
  left join public.profiles p on p.id = c.authorid
  where c.id = p_collection_id
    and c.authorid = v_user_id
  limit 1;
end;
$$;

comment on function public.get_current_user_module_collection_by_id(bigint) is
  'Current-user module collection detail read by numeric id.';

create or replace function public.get_module_collections_for_module(
  p_module_id bigint
)
returns table (
  id bigint,
  authorid uuid,
  name text,
  description text,
  image text,
  public boolean,
  public_id text,
  created timestamp without time zone,
  updated timestamp without time zone,
  author jsonb,
  module_count integer
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
begin
  return query
  select
    c.id,
    c.authorid,
    c.name,
    c.description,
    c.image,
    c.public,
    c.public_id,
    c.created,
    c.updated,
    jsonb_build_object('id', p.id, 'username', p.username) as author,
    coalesce((
      select count(*)
      from public.module_collection_entries e2
      join public.modules m2 on m2.id = e2.module_id and m2.public = true
      where e2.collection_id = c.id
    ), 0)::int as module_count
  from public.module_collections c
  left join public.profiles p on p.id = c.authorid
  where (
    c.public = true
    or c.authorid = v_user_id
  )
    and exists (
      select 1
      from public.module_collection_entries e
      join public.modules m on m.id = e.module_id and m.public = true
      where e.collection_id = c.id
        and e.module_id = p_module_id
    )
  order by c.updated desc, c.id desc;
end;
$$;

comment on function public.get_module_collections_for_module(bigint) is
  'Lists public collections that include the requested public module, plus the current user''s own collections when signed in.';

grant execute on function public.save_module_collection(text, bigint, text, boolean, text, bigint[]) to authenticated;
grant execute on function public.delete_module_collection(bigint) to authenticated;
grant execute on function public.get_public_module_collections(int, int) to anon, authenticated;
grant execute on function public.get_current_user_module_collections(int, int) to authenticated;
grant execute on function public.get_public_module_collection_by_public_id(text) to anon, authenticated;
grant execute on function public.get_current_user_module_collection_by_id(bigint) to authenticated;
grant execute on function public.get_module_collections_for_module(bigint) to anon, authenticated;
