-- Price Hub experimental store snapshot pilot: additive schema only.
-- Approved 2026-07-02 for remote schema application only. No RLS, policies,
-- GRANTs, SECURITY DEFINER functions, cron, or listing backfill are included here.

create table if not exists public.stores (
  id bigint generated by default as identity primary key,
  slug text not null,
  name text not null,
  country_code char(2),
  base_url text not null,
  search_url_template text,
  adapter_kind text not null default 'none',
  currency_hint char(3),
  active boolean not null default true,
  price_tracking_enabled boolean not null default false,
  rate_limit_per_day integer not null default 20,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint stores_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint stores_name_not_blank check (length(btrim(name)) > 0),
  constraint stores_country_code_format check (country_code is null or country_code ~ '^[A-Z]{2}$'),
  constraint stores_base_url_https check (base_url ~ '^https://'),
  constraint stores_search_url_template_https check (search_url_template is null or search_url_template ~ '^https://'),
  constraint stores_adapter_kind_check check (adapter_kind in ('woocommerce_store_api', 'shopify_product_json', 'bigcommerce_metadata', 'shopware_metadata', 'custom', 'none')),
  constraint stores_currency_hint_format check (currency_hint is null or currency_hint ~ '^[A-Z]{3}$'),
  constraint stores_rate_limit_per_day_check check (rate_limit_per_day between 1 and 500),
  constraint stores_slug_unique unique (slug)
);

create table if not exists public.module_store_listings (
  id bigint generated by default as identity primary key,
  module_id bigint not null references public.modules(id) on delete cascade,
  store_id bigint not null references public.stores(id) on delete cascade,
  product_url text not null,
  external_product_id text,
  external_handle text,
  active boolean not null default true,
  verification_status text not null default 'candidate',
  last_checked_at timestamp with time zone,
  last_success_at timestamp with time zone,
  next_check_at timestamp with time zone not null default now(),
  failure_count integer not null default 0,
  last_error text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint module_store_listings_product_url_https check (product_url ~ '^https://'),
  constraint module_store_listings_verification_status_check check (verification_status in ('candidate', 'verified', 'rejected', 'stale')),
  constraint module_store_listings_failure_count_check check (failure_count >= 0),
  constraint module_store_listings_last_error_length check (last_error is null or char_length(last_error) <= 1000),
  constraint module_store_listings_module_store_unique unique (module_id, store_id),
  constraint module_store_listings_store_url_unique unique (store_id, product_url)
);

create table if not exists public.module_price_snapshots (
  id bigint generated by default as identity primary key,
  listing_id bigint not null references public.module_store_listings(id) on delete cascade,
  observed_at timestamp with time zone not null default now(),
  price_amount_minor bigint,
  currency char(3),
  availability text not null default 'unknown',
  source text not null default 'api',
  raw_meta jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default now(),
  constraint module_price_snapshots_price_non_negative check (price_amount_minor is null or price_amount_minor >= 0),
  constraint module_price_snapshots_currency_format check (currency is null or currency ~ '^[A-Z]{3}$'),
  constraint module_price_snapshots_price_currency_pair check (price_amount_minor is null or currency is not null),
  constraint module_price_snapshots_availability_check check (availability in ('in_stock', 'out_of_stock', 'preorder', 'backorder', 'discontinued', 'unknown')),
  constraint module_price_snapshots_source_check check (source in ('scraper', 'api', 'manual', 'community', 'manufacturer')),
  constraint module_price_snapshots_raw_meta_object check (jsonb_typeof(raw_meta) = 'object')
);

create index if not exists stores_adapter_tracking_idx
  on public.stores (adapter_kind, active, price_tracking_enabled);

create index if not exists module_store_listings_due_idx
  on public.module_store_listings (active, next_check_at, id)
  where active = true;

create index if not exists module_store_listings_module_idx
  on public.module_store_listings (module_id, store_id);

create index if not exists module_store_listings_store_idx
  on public.module_store_listings (store_id, next_check_at);

create index if not exists module_price_snapshots_listing_latest_idx
  on public.module_price_snapshots (listing_id, observed_at desc, id desc);

create index if not exists module_price_snapshots_observed_idx
  on public.module_price_snapshots (observed_at desc);

create or replace function public.tg_price_hub_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

comment on function public.tg_price_hub_set_updated_at() is
  'BEFORE UPDATE trigger for Price Hub pilot tables with updated_at columns.';

drop trigger if exists trg_stores_updated_at on public.stores;
create trigger trg_stores_updated_at
  before update on public.stores
  for each row execute function public.tg_price_hub_set_updated_at();

drop trigger if exists trg_module_store_listings_updated_at on public.module_store_listings;
create trigger trg_module_store_listings_updated_at
  before update on public.module_store_listings
  for each row execute function public.tg_price_hub_set_updated_at();

insert into public.stores (
  slug,
  name,
  country_code,
  base_url,
  search_url_template,
  adapter_kind,
  currency_hint,
  active,
  price_tracking_enabled,
  rate_limit_per_day
)
values
  (
    'elevator-sound',
    'Elevator Sound',
    'GB',
    'https://www.elevatorsound.com/',
    'https://www.elevatorsound.com/?s={query}&post_type=product',
    'woocommerce_store_api',
    'GBP',
    true,
    true,
    20
  ),
  (
    'new-groove',
    'New Groove',
    'IT',
    'https://newgroove.it/',
    'https://newgroove.it/?s={query}&post_type=product',
    'woocommerce_store_api',
    'EUR',
    true,
    true,
    20
  ),
  (
    'signal-sounds-uk',
    'Signal Sounds UK',
    'GB',
    'https://www.signalsounds.com/',
    'https://www.signalsounds.com/search.php?search_query={query}',
    'bigcommerce_metadata',
    'GBP',
    true,
    true,
    100
  ),
  (
    'signal-sounds-eu',
    'Signal Sounds EU',
    'PL',
    'https://signalsounds.eu/',
    'https://signalsounds.eu/search.php?search_query={query}',
    'bigcommerce_metadata',
    'EUR',
    true,
    true,
    100
  ),
  (
    'schneidersladen',
    'SchneidersLaden',
    'DE',
    'https://schneidersladen.de/en/',
    'https://schneidersladen.de/en/search?search={query}',
    'shopware_metadata',
    'EUR',
    true,
    true,
    100
  )
on conflict (slug) do nothing;

-- Intentionally no module_store_listings seed rows: curated rows need real module IDs
-- and canonical store product URLs, and guessing those would risk wrong snapshots.
