create table if not exists public.user_module_acquisitions (
  id bigint generated by default as identity primary key,
  profileid uuid not null references public.profiles(id) on delete cascade,
  moduleid bigint not null references public.modules(id) on delete cascade,
  acquired_at date not null default current_date,
  price_amount_minor bigint null check (price_amount_minor >= 0),
  currency text null,
  source text not null default 'unknown',
  note text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_module_acquisitions_currency_check
    check (currency is null or currency in ('EUR', 'USD')),
  constraint user_module_acquisitions_price_currency_check
    check (
      (price_amount_minor is null and currency is null)
      or (price_amount_minor is not null and currency is not null)
    ),
  constraint user_module_acquisitions_source_check
    check (source in ('unknown', 'new', 'used', 'gift', 'trade', 'marketplace', 'other')),
  constraint user_module_acquisitions_note_length_check
    check (note is null or char_length(note) <= 500)
);

alter table public.user_module_acquisitions enable row level security;

create policy "user_module_acquisitions_select_own"
  on public.user_module_acquisitions
  for select
  using (auth.uid() = profileid);

create policy "user_module_acquisitions_insert_own"
  on public.user_module_acquisitions
  for insert
  with check (auth.uid() = profileid);

create policy "user_module_acquisitions_update_own"
  on public.user_module_acquisitions
  for update
  using (auth.uid() = profileid)
  with check (auth.uid() = profileid);

create policy "user_module_acquisitions_delete_own"
  on public.user_module_acquisitions
  for delete
  using (auth.uid() = profileid);

create index if not exists user_module_acquisitions_owner_idx
  on public.user_module_acquisitions (profileid);

create index if not exists user_module_acquisitions_owner_module_latest_idx
  on public.user_module_acquisitions (profileid, moduleid, acquired_at desc, id desc);

create index if not exists user_module_acquisitions_module_idx
  on public.user_module_acquisitions (moduleid);
