-- Manufacturer ownership claims and approval side effects.

create table if not exists public.manufacturer_claims (
  id bigint generated by default as identity primary key,
  manufacturer_id integer not null references public.manufacturers(id) on delete cascade,
  claimant_id uuid not null references public.profiles(id) on delete cascade,
  proof_note text not null,
  status text not null default 'pending',
  admin_note text null,
  decided_at timestamptz null,
  decided_by uuid null references public.profiles(id) on delete set null,
  created timestamptz not null default now(),
  updated timestamptz not null default now(),
  constraint manufacturer_claims_proof_note_not_blank check (length(btrim(proof_note)) > 0),
  constraint manufacturer_claims_status_check check (
    status in ('pending', 'approved', 'rejected', 'needs_more_info')
  )
);

create index if not exists manufacturer_claims_manufacturer_status_idx
  on public.manufacturer_claims (manufacturer_id, status);

create unique index if not exists manufacturer_claims_one_pending_per_manufacturer_idx
  on public.manufacturer_claims (manufacturer_id)
  where status = 'pending';

create unique index if not exists manufacturer_claims_one_pending_per_claimant_idx
  on public.manufacturer_claims (claimant_id)
  where status = 'pending';

create or replace function public.tg_touch_manufacturer_claims_updated()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  NEW.updated = now();
  return NEW;
end;
$$;

comment on function public.tg_touch_manufacturer_claims_updated() is
  'BEFORE UPDATE trigger: keeps manufacturer_claims.updated aligned with claim changes.';

drop trigger if exists trg_touch_manufacturer_claims_updated on public.manufacturer_claims;
create trigger trg_touch_manufacturer_claims_updated
  before update on public.manufacturer_claims
  for each row execute function public.tg_touch_manufacturer_claims_updated();

create or replace function public.tg_apply_manufacturer_claim_decision()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if NEW.status is distinct from OLD.status
     and NEW.status in ('approved', 'rejected', 'needs_more_info') then
    NEW.decided_at = coalesce(NEW.decided_at, now());
    NEW.decided_by = coalesce(NEW.decided_by, auth.uid());
  end if;

  if OLD.status is distinct from NEW.status and NEW.status = 'approved' then
    update public.manufacturers
       set "adminUser" = NEW.claimant_id::text,
           verified_at = coalesce(NEW.decided_at, now()),
           verified_by = coalesce(NEW.decided_by, auth.uid())
     where id = NEW.manufacturer_id;
  end if;

  return NEW;
end;
$$;

comment on function public.tg_apply_manufacturer_claim_decision() is
  'BEFORE UPDATE trigger: records claim decisions and promotes approved claimants to verified manufacturer owners.';

drop trigger if exists trg_apply_manufacturer_claim_decision on public.manufacturer_claims;
create trigger trg_apply_manufacturer_claim_decision
  before update of status on public.manufacturer_claims
  for each row execute function public.tg_apply_manufacturer_claim_decision();

alter table public.manufacturer_claims enable row level security;

drop policy if exists "manufacturer_claims_insert_own_pending" on public.manufacturer_claims;
create policy "manufacturer_claims_insert_own_pending"
  on public.manufacturer_claims
  for insert
  to authenticated
  with check (
    claimant_id = auth.uid()
    and status = 'pending'
    and decided_at is null
    and decided_by is null
  );

drop policy if exists "manufacturer_claims_select_own_or_admin" on public.manufacturer_claims;
create policy "manufacturer_claims_select_own_or_admin"
  on public.manufacturer_claims
  for select
  to authenticated
  using (
    claimant_id = auth.uid()
    or coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin'
  );

drop policy if exists "manufacturer_claims_update_admin" on public.manufacturer_claims;
create policy "manufacturer_claims_update_admin"
  on public.manufacturer_claims
  for update
  to authenticated
  using (
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin'
  )
  with check (
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin'
  );

drop policy if exists "manufacturer_claims_delete_pending_own_or_admin" on public.manufacturer_claims;
create policy "manufacturer_claims_delete_pending_own_or_admin"
  on public.manufacturer_claims
  for delete
  to authenticated
  using (
    (claimant_id = auth.uid() and status = 'pending')
    or coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin'
  );
