name: Angular Tests

on:
  push:
    branches:
      - '*'  # Trigger on all branches

jobs:
  build:
    runs-on: [x64]
    timeout-minutes: 8
    if: github.event_name == 'push'  # Only trigger on pushes
    steps:
      - name: Check if this is the latest commit
        id: latest_commit_check
        run: |
          # Use regular parentheses for comparison in PowerShell
          latestCommit=$(git rev-parse HEAD)
          latestRef=$(git for-each-ref --sort=-committerdate refs/heads/ --format '%(objectname)%(refname)' | awk 'NR==1{print $2}')
          if ($latestCommit -eq $latestRef) {
            echo "::set-output name=is_latest_commit::true"
          } else {
            echo "::set-output name=is_latest_commit::false"
          }

      - name: Paths Changes Filter
        uses: dorny/paths-filter@v2.11.1
        with:
          filters: |
            src:
              - 'src/**'

      - name: Setup Node.js
        if: steps.latest_commit_check.outputs.is_latest_commit == 'true'
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'  

      - name: Install Angular CLI
        if: steps.latest_commit_check.outputs.is_latest_commit == 'true'
        run: yarn global add @angular/cli # Use Yarn to install Angular CLI

      - name: Cache Yarn dependencies
        if: steps.latest_commit_check.outputs.is_latest_commit == 'true'
        uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Clear Yarn Cache
        if: steps.latest_commit_check.outputs.is_latest_commit == 'true'
        run: yarn cache clean

      - name: Install dependencies
        if: steps.latest_commit_check.outputs.is_latest_commit == 'true'
        run: yarn install # Use Yarn to install dependencies

      - name: Run tests
        if: steps.latest_commit_check.outputs.is_latest_commit == 'true'
        run: yarn test-headless # Use Yarn to run tests
