name: Angular Tests and Deploy
on: push
permissions: read-all

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Change working directory
        run: cd ${{ github.workspace }}
      - run: npm test
