name: Angular Tests

on:
  push:
    branches:
      - develop
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Print environment variables
        run: printenv

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: ng test --verbose
