name: Angular Tests
on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: [x64]
    timeout-minutes: 8
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install Angular CLI
        run: yarn global add @angular/cli # Use Yarn to install Angular CLI

      - name: Cache Yarn dependencies # Change from npm to Yarn caching
        uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }} # Update the key for Yarn
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Clear Yarn Cache
        run: yarn cache clean

      - name: Install dependencies
        run: yarn install # Use Yarn to install dependencies

      - name: Run tests
        run: yarn test-headless # Use Yarn to run tests
