name: Audit

on:
  push:
    branches:
      - production
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Audit live URL
        uses: jakejarvis/lighthouse-action@master
        with:
          url: 'https://patcher.xyz/'
      - name: Upload results as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: './report'
