on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - production
    paths-ignore:
      - 'internaldocs/**'
      - '**/*.md'
      - '**/*.txt'
      - '.github/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - 'internaldocs/**'
      - '**/*.md'
      - '**/*.txt'
      - '.github/**'

name: CodeSee Map

permissions: read-all

env:
  COREPACK_ENABLE_DOWNLOAD_PROMPT: '0'

defaults:
  run:
    shell: bash

jobs:
  codesee:
    runs-on: ubuntu-latest
    continue-on-error: true
    name: Analyse the repo with CodeSee
    steps:
      - name: Run CodeSee analysis
        uses: Codesee-io/codesee-action@v2
        with:
          codesee-token: ${{ secrets.CODESEE_ARCH_DIAG_API_TOKEN }}
